language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

sudo: required

services:
  - docker

script:
  - sbt +test

cache:
  directories:
  - $HOME/.gradle

branches:
  only:
  - master
  - sbt # TODO remove